server:
  port: 8083

spring:
  application:
    name: cloud-consumer-order
  #### consul注册中心地址
  cloud:
    consul:
      host: 47.95.211.172
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true