server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      discovery:
        locator:
          enabled: true
      routes:
        #路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #uri 的协议为 lb，表示启用 GateWay 的负载均衡功能、配置动态路由
          uri: lb://cloud-payment-service
          predicates:
            #断言，路径相匹配的进行路由
            - Path=/payment/get/**

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            #配置访问路径
            - Path=/payment/lb/**
#            #配置时间之后、时间之前、时间范围内可以访问
#            - After=2023-01-06T20:05:04.677+08:00[Asia/Shanghai]
#            - Before=2023-01-06T20:05:04.677+08:00[Asia/Shanghai]
#            - Between=2023-01-06T19:05:04.677+08:00[Asia/Shanghai],2023-01-06T20:05:04.677+08:00[Asia/Shanghai]
#            #配置通过获取对应的cookie name 和 正则表达式去匹配，测试：curl http://127.0.0.1:9527/payment/lb --cookie "username=hshuo"
#            - Cookie=username,hshuo
#            #配置请求头含有X-Request-Id属性并且值为正数的正则表达式匹配，测试：curl http://127.0.0.1:9527/payment/lb -H "X-Request-Id:123"
#            - Header=X-Request-Id, \d+
#            #配置匹配的主机为**.hshuo.com，测试：curl http://127.0.0.1:9527/payment/lb -H "Host: com.hshuo.com"
#            - Host=**.hshuo.com
#            #配置匹配的请求类型为 GET，测试：curl -X -POST http://127.0.0.1:9527/payment/lb
#            - Method=GET
#            ##配置要有参数名username并且值为正数才能路由，测试：curl http://localhost:9527/payment/lb?username=31
#            - Query=username, \d+
#          filters:
#            #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
#            - AddRequestParameter=X-Request-Id,1024


eureka:
  instance:
    hostname: cloud-gateway-service
  #服务提供者provider注册进eureka服务列表内
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#      defaultZone: http://eureka7001.com:7001/eureka